### ISSUE TITLE
Package Fix Version Notation Should be YYYYMMDD so that December 1 is higher than November 2

### ISSUE THREAD

**Issue by ferventcoder** [majkinetor/chocolatey#20]
I probably created this at the wrong repository, but this appears related to https://github.com/majkinetor/au/issues/13

* https://chocolatey.org/packages/dbeaver/3.7.2.20160708
* https://chocolatey.org/packages/eac/1.1.20160708
* https://chocolatey.org/packages/ampfontviewer/3.8.6.20160708
* https://chocolatey.org/packages/trid/2.20.20160708
* https://chocolatey.org/packages/nexus-oss/2.13.0.0120160708
* https://chocolatey.org/packages/wzgrapher/0.95.20160708

Let me know what you want me to do with these. It could not hurt to approve them as is for now as the day was less than the month.

What do you want to do with 
* https://chocolatey.org/packages/wkhtmltopdf/0.12.3.220160708
* https://chocolatey.org/packages/dngrep/2.8.16.020160708

**Comment by majkinetor** [comment]
Aprove them. It was a manual mistake but its not that important, right ? If you insist I can fix them. Eac may be rejected since new version was out a few days later.

> https://chocolatey.org/packages/wkhtmltopdf/0.12.3.220160708
> https://chocolatey.org/packages/dngrep/2.8.16.020160708

Those had already number in the revision so I had to use different notation. I think it doesn't hurt to stay that way. Dngrep will probably stop updatring as the project seem stalled so I want its choco package to have a checksum and wkhtmltopdf gets update regularly so it will soon get a new regular version.

Sorry for inconvenience. With au having this feature it wont happen again.

**Comment by majkinetor** [comment]
BTW, its not `YYYYMMDD` but `yyyyMMdd` -  ISO 8601 format.

**Comment by ferventcoder** [comment]
Ha, I wasn't getting technical on the *exact* format

**Comment by ferventcoder** [comment]
Looks like this is completed.
